import { test, expect } from 'vitest'
import { extractLinks } from '../extractLinks.js'

const statuses = [
  {
    id: '110612711710168997',
    uri: 'https://mastodon.social/users/fstackbulletin/statuses/110612711710168997',
    url: 'https://mastodon.social/@fstackbulletin/110612711710168997',
    account: {
      id: '110612338021214317',
      username: 'fstackbulletin',
      acct: 'fstackbulletin',
      display_name: 'FullStack Bulletin',
      locked: false,
      bot: false,
      discoverable: true,
      group: false,
      created_at: '2023-06-26T00:00:00.000Z',
      note: '<p>The (self-proclaimed) most awesome weekly <a href="https://mastodon.social/tags/newsletter" class="mention hashtag" rel="tag">#<span>newsletter</span></a> about <a href="https://mastodon.social/tags/fullstack" class="mention hashtag" rel="tag">#<span>fullstack</span></a> <a href="https://mastodon.social/tags/web" class="mention hashtag" rel="tag">#<span>web</span></a> <a href="https://mastodon.social/tags/development" class="mention hashtag" rel="tag">#<span>development</span></a> — Manually curated by andreaman87 &amp; loige.co</p>',
      url: 'https://mastodon.social/@fstackbulletin',
      avatar: 'https://files.mastodon.social/accounts/avatars/110/612/338/021/214/317/original/72888a67caa2555a.jpg',
      avatar_static: 'https://files.mastodon.social/accounts/avatars/110/612/338/021/214/317/original/72888a67caa2555a.jpg',
      header: 'https://mastodon.social/headers/original/missing.png',
      header_static: 'https://mastodon.social/headers/original/missing.png',
      followers_count: 1,
      following_count: 1,
      statuses_count: 7,
      last_status_at: '2023-06-26',
      noindex: false,
      emojis: [],
      roles: [],
      fields: [
        {
          name: 'Website',
          value: '<a href="https://fullstackbulletin.com" target="_blank" rel="nofollow noopener noreferrer me" translate="no"><span class="invisible">https://</span><span class="">fullstackbulletin.com</span><span class="invisible"></span></a>',
          verified_at: null
        }
      ]
    },
    in_reply_to_id: null,
    in_reply_to_account_id: null,
    reblog: null,
    content: '<p>What is a CDN? An Unbiased Guide to Content Delivery Networks</p><p><a href="https://calibreapp.com/blog/content-delivery-networks-guide" target="_blank" rel="nofollow noopener noreferrer" translate="no"><span class="invisible">https://</span><span class="ellipsis">calibreapp.com/blog/content-de</span><span class="invisible">livery-networks-guide</span></a></p>',
    plain_content: null,
    created_at: '2023-06-26T21:47:15.617Z',
    emojis: [],
    replies_count: 0,
    reblogs_count: 1,
    favourites_count: 1,
    reblogged: false,
    favourited: false,
    muted: false,
    sensitive: false,
    spoiler_text: '',
    visibility: 'public',
    media_attachments: [],
    mentions: [],
    tags: [],
    card: {
      url: 'https://calibreapp.com/blog/content-delivery-networks-guide',
      title: 'What is a CDN? An Unbiased Guide to Content Delivery Networks - Calibre ',
      description: 'A fast and resilient content delivery network is one of the best ways to improve the performance of your site. Here’s how to make an informed decision when choosing one.',
      language: 'en',
      type: 'link',
      author_name: '',
      author_url: '',
      provider_name: 'Calibre - Site Speed Tools for Teams',
      provider_url: '',
      html: '',
      width: 1200,
      height: 630,
      image: 'https://files.mastodon.social/cache/preview_cards/images/064/575/183/original/4231251ad10776a6.jpg',
      embed_url: '',
      blurhash: 'UMDAGxE4tmM{DNnNaJM{EMtmaxofMxV?s:%M'
    },
    poll: null,
    application: {
      name: 'Web',
      website: null
    },
    language: 'en',
    pinned: false,
    emoji_reactions: [],
    bookmarked: false,
    quote: false
  },
  {
    id: '110612710413754921',
    uri: 'https://mastodon.social/users/fstackbulletin/statuses/110612710413754921',
    url: 'https://mastodon.social/@fstackbulletin/110612710413754921',
    account: {
      id: '110612338021214317',
      username: 'fstackbulletin',
      acct: 'fstackbulletin',
      display_name: 'FullStack Bulletin',
      locked: false,
      bot: false,
      discoverable: true,
      group: false,
      created_at: '2023-06-26T00:00:00.000Z',
      note: '<p>The (self-proclaimed) most awesome weekly <a href="https://mastodon.social/tags/newsletter" class="mention hashtag" rel="tag">#<span>newsletter</span></a> about <a href="https://mastodon.social/tags/fullstack" class="mention hashtag" rel="tag">#<span>fullstack</span></a> <a href="https://mastodon.social/tags/web" class="mention hashtag" rel="tag">#<span>web</span></a> <a href="https://mastodon.social/tags/development" class="mention hashtag" rel="tag">#<span>development</span></a> — Manually curated by andreaman87 &amp; loige.co</p>',
      url: 'https://mastodon.social/@fstackbulletin',
      avatar: 'https://files.mastodon.social/accounts/avatars/110/612/338/021/214/317/original/72888a67caa2555a.jpg',
      avatar_static: 'https://files.mastodon.social/accounts/avatars/110/612/338/021/214/317/original/72888a67caa2555a.jpg',
      header: 'https://mastodon.social/headers/original/missing.png',
      header_static: 'https://mastodon.social/headers/original/missing.png',
      followers_count: 1,
      following_count: 1,
      statuses_count: 7,
      last_status_at: '2023-06-26',
      noindex: false,
      emojis: [],
      roles: [],
      fields: [
        {
          name: 'Website',
          value: '<a href="https://fullstackbulletin.com" target="_blank" rel="nofollow noopener noreferrer me" translate="no"><span class="invisible">https://</span><span class="">fullstackbulletin.com</span><span class="invisible"></span></a>',
          verified_at: null
        }
      ]
    },
    in_reply_to_id: null,
    in_reply_to_account_id: null,
    reblog: null,
    content: '<p>Is there a viable animated GIF alternative yet or what?</p><p><a href="https://cloudfour.com/thinks/animated-gif-alternative/" target="_blank" rel="nofollow noopener noreferrer" translate="no"><span class="invisible">https://</span><span class="ellipsis">cloudfour.com/thinks/animated-</span><span class="invisible">gif-alternative/</span></a></p>',
    plain_content: null,
    created_at: '2023-06-26T21:46:55.835Z',
    emojis: [],
    replies_count: 0,
    reblogs_count: 0,
    favourites_count: 0,
    reblogged: false,
    favourited: false,
    muted: false,
    sensitive: false,
    spoiler_text: '',
    visibility: 'public',
    media_attachments: [],
    mentions: [],
    tags: [],
    card: {
      url: 'https://cloudfour.com/thinks/animated-gif-alternative/',
      title: 'Is there a viable animated GIF alternative yet or what?',
      description: 'Animated GIFs remain popular in spite of their beefy file sizes. But what are we supposed to use instead?',
      language: 'en',
      type: 'link',
      author_name: '',
      author_url: '',
      provider_name: 'Cloud Four',
      provider_url: '',
      html: '',
      width: 1200,
      height: 675,
      image: 'https://files.mastodon.social/cache/preview_cards/images/063/427/039/original/60fbbf7209260eb6.jpg',
      embed_url: '',
      blurhash: 'USGBDAj]46ScPTnPvhTIJ6a}$Qn*z^baKenP'
    },
    poll: null,
    application: {
      name: 'Web',
      website: null
    },
    language: 'en',
    pinned: false,
    emoji_reactions: [],
    bookmarked: false,
    quote: false
  },
  {
    id: '110612707595198426',
    uri: 'https://mastodon.social/users/fstackbulletin/statuses/110612707595198426',
    url: 'https://mastodon.social/@fstackbulletin/110612707595198426',
    account: {
      id: '110612338021214317',
      username: 'fstackbulletin',
      acct: 'fstackbulletin',
      display_name: 'FullStack Bulletin',
      locked: false,
      bot: false,
      discoverable: true,
      group: false,
      created_at: '2023-06-26T00:00:00.000Z',
      note: '<p>The (self-proclaimed) most awesome weekly <a href="https://mastodon.social/tags/newsletter" class="mention hashtag" rel="tag">#<span>newsletter</span></a> about <a href="https://mastodon.social/tags/fullstack" class="mention hashtag" rel="tag">#<span>fullstack</span></a> <a href="https://mastodon.social/tags/web" class="mention hashtag" rel="tag">#<span>web</span></a> <a href="https://mastodon.social/tags/development" class="mention hashtag" rel="tag">#<span>development</span></a> — Manually curated by andreaman87 &amp; loige.co</p>',
      url: 'https://mastodon.social/@fstackbulletin',
      avatar: 'https://files.mastodon.social/accounts/avatars/110/612/338/021/214/317/original/72888a67caa2555a.jpg',
      avatar_static: 'https://files.mastodon.social/accounts/avatars/110/612/338/021/214/317/original/72888a67caa2555a.jpg',
      header: 'https://mastodon.social/headers/original/missing.png',
      header_static: 'https://mastodon.social/headers/original/missing.png',
      followers_count: 1,
      following_count: 1,
      statuses_count: 7,
      last_status_at: '2023-06-26',
      noindex: false,
      emojis: [],
      roles: [],
      fields: [
        {
          name: 'Website',
          value: '<a href="https://fullstackbulletin.com" target="_blank" rel="nofollow noopener noreferrer me" translate="no"><span class="invisible">https://</span><span class="">fullstackbulletin.com</span><span class="invisible"></span></a>',
          verified_at: null
        }
      ]
    },
    in_reply_to_id: null,
    in_reply_to_account_id: null,
    reblog: null,
    content: '<p>Hyperfetch: a framework for request and realtime connection.</p><p><a href="https://hyperfetch.bettertyped.com/" target="_blank" rel="nofollow noopener noreferrer" translate="no"><span class="invisible">https://</span><span class="">hyperfetch.bettertyped.com/</span><span class="invisible"></span></a></p>',
    plain_content: null,
    created_at: '2023-06-26T21:46:12.829Z',
    emojis: [],
    replies_count: 0,
    reblogs_count: 0,
    favourites_count: 0,
    reblogged: false,
    favourited: false,
    muted: false,
    sensitive: false,
    spoiler_text: '',
    visibility: 'public',
    media_attachments: [],
    mentions: [],
    tags: [],
    card: {
      url: 'https://hyperfetch.bettertyped.com/',
      title: 'Data Fetching, Offline First, Caching, Queueing | Hyper Fetch',
      description: 'Framework for requesting and realtime connection',
      language: 'en',
      type: 'link',
      author_name: '',
      author_url: '',
      provider_name: '',
      provider_url: '',
      html: '',
      width: 0,
      height: 0,
      image: null,
      embed_url: '',
      blurhash: null
    },
    poll: null,
    application: {
      name: 'Web',
      website: null
    },
    language: 'en',
    pinned: false,
    emoji_reactions: [],
    bookmarked: false,
    quote: false
  },
  {
    id: '110612705956095549',
    uri: 'https://mastodon.social/users/fstackbulletin/statuses/110612705956095549',
    url: 'https://mastodon.social/@fstackbulletin/110612705956095549',
    account: {
      id: '110612338021214317',
      username: 'fstackbulletin',
      acct: 'fstackbulletin',
      display_name: 'FullStack Bulletin',
      locked: false,
      bot: false,
      discoverable: true,
      group: false,
      created_at: '2023-06-26T00:00:00.000Z',
      note: '<p>The (self-proclaimed) most awesome weekly <a href="https://mastodon.social/tags/newsletter" class="mention hashtag" rel="tag">#<span>newsletter</span></a> about <a href="https://mastodon.social/tags/fullstack" class="mention hashtag" rel="tag">#<span>fullstack</span></a> <a href="https://mastodon.social/tags/web" class="mention hashtag" rel="tag">#<span>web</span></a> <a href="https://mastodon.social/tags/development" class="mention hashtag" rel="tag">#<span>development</span></a> — Manually curated by andreaman87 &amp; loige.co</p>',
      url: 'https://mastodon.social/@fstackbulletin',
      avatar: 'https://files.mastodon.social/accounts/avatars/110/612/338/021/214/317/original/72888a67caa2555a.jpg',
      avatar_static: 'https://files.mastodon.social/accounts/avatars/110/612/338/021/214/317/original/72888a67caa2555a.jpg',
      header: 'https://mastodon.social/headers/original/missing.png',
      header_static: 'https://mastodon.social/headers/original/missing.png',
      followers_count: 1,
      following_count: 1,
      statuses_count: 7,
      last_status_at: '2023-06-26',
      noindex: false,
      emojis: [],
      roles: [],
      fields: [
        {
          name: 'Website',
          value: '<a href="https://fullstackbulletin.com" target="_blank" rel="nofollow noopener noreferrer me" translate="no"><span class="invisible">https://</span><span class="">fullstackbulletin.com</span><span class="invisible"></span></a>',
          verified_at: null
        }
      ]
    },
    in_reply_to_id: null,
    in_reply_to_account_id: null,
    reblog: null,
    content: '<p>The GROQ specification: a new language to search, filter and manipulate JSON and JSONnd files</p><p><a href="https://sanity-io.github.io/GROQ/GROQ-1.revision1/" target="_blank" rel="nofollow noopener noreferrer" translate="no"><span class="invisible">https://</span><span class="ellipsis">sanity-io.github.io/GROQ/GROQ-</span><span class="invisible">1.revision1/</span></a></p>',
    plain_content: null,
    created_at: '2023-06-26T21:45:47.820Z',
    emojis: [],
    replies_count: 0,
    reblogs_count: 0,
    favourites_count: 0,
    reblogged: false,
    favourited: false,
    muted: false,
    sensitive: false,
    spoiler_text: '',
    visibility: 'public',
    media_attachments: [],
    mentions: [],
    tags: [],
    card: {
      url: 'https://sanity-io.github.io/GROQ/GROQ-1.revision1/',
      title: 'GROQ',
      description: '',
      language: null,
      type: 'link',
      author_name: '',
      author_url: '',
      provider_name: '',
      provider_url: '',
      html: '',
      width: 0,
      height: 0,
      image: null,
      embed_url: '',
      blurhash: null
    },
    poll: null,
    application: {
      name: 'Web',
      website: null
    },
    language: 'en',
    pinned: false,
    emoji_reactions: [],
    bookmarked: false,
    quote: false
  },
  {
    id: '110612704850091520',
    uri: 'https://mastodon.social/users/fstackbulletin/statuses/110612704850091520',
    url: 'https://mastodon.social/@fstackbulletin/110612704850091520',
    account: {
      id: '110612338021214317',
      username: 'fstackbulletin',
      acct: 'fstackbulletin',
      display_name: 'FullStack Bulletin',
      locked: false,
      bot: false,
      discoverable: true,
      group: false,
      created_at: '2023-06-26T00:00:00.000Z',
      note: '<p>The (self-proclaimed) most awesome weekly <a href="https://mastodon.social/tags/newsletter" class="mention hashtag" rel="tag">#<span>newsletter</span></a> about <a href="https://mastodon.social/tags/fullstack" class="mention hashtag" rel="tag">#<span>fullstack</span></a> <a href="https://mastodon.social/tags/web" class="mention hashtag" rel="tag">#<span>web</span></a> <a href="https://mastodon.social/tags/development" class="mention hashtag" rel="tag">#<span>development</span></a> — Manually curated by andreaman87 &amp; loige.co</p>',
      url: 'https://mastodon.social/@fstackbulletin',
      avatar: 'https://files.mastodon.social/accounts/avatars/110/612/338/021/214/317/original/72888a67caa2555a.jpg',
      avatar_static: 'https://files.mastodon.social/accounts/avatars/110/612/338/021/214/317/original/72888a67caa2555a.jpg',
      header: 'https://mastodon.social/headers/original/missing.png',
      header_static: 'https://mastodon.social/headers/original/missing.png',
      followers_count: 1,
      following_count: 1,
      statuses_count: 7,
      last_status_at: '2023-06-26',
      noindex: false,
      emojis: [],
      roles: [],
      fields: [
        {
          name: 'Website',
          value: '<a href="https://fullstackbulletin.com" target="_blank" rel="nofollow noopener noreferrer me" translate="no"><span class="invisible">https://</span><span class="">fullstackbulletin.com</span><span class="invisible"></span></a>',
          verified_at: null
        }
      ]
    },
    in_reply_to_id: null,
    in_reply_to_account_id: null,
    reblog: null,
    content: '<p>The .meta folder proposal: let&#39;s tidy up all these config files mess!</p><p><a href="https://dotmeta.org" target="_blank" rel="nofollow noopener noreferrer" translate="no"><span class="invisible">https://</span><span class="">dotmeta.org</span><span class="invisible"></span></a></p>',
    plain_content: null,
    created_at: '2023-06-26T21:45:30.941Z',
    emojis: [],
    replies_count: 0,
    reblogs_count: 0,
    favourites_count: 0,
    reblogged: false,
    favourited: false,
    muted: false,
    sensitive: false,
    spoiler_text: '',
    visibility: 'public',
    media_attachments: [],
    mentions: [],
    tags: [],
    card: null,
    poll: null,
    application: {
      name: 'Web',
      website: null
    },
    language: 'en',
    pinned: false,
    emoji_reactions: [],
    bookmarked: false,
    quote: false
  },
  {
    id: '110612703713147028',
    uri: 'https://mastodon.social/users/fstackbulletin/statuses/110612703713147028',
    url: 'https://mastodon.social/@fstackbulletin/110612703713147028',
    account: {
      id: '110612338021214317',
      username: 'fstackbulletin',
      acct: 'fstackbulletin',
      display_name: 'FullStack Bulletin',
      locked: false,
      bot: false,
      discoverable: true,
      group: false,
      created_at: '2023-06-26T00:00:00.000Z',
      note: '<p>The (self-proclaimed) most awesome weekly <a href="https://mastodon.social/tags/newsletter" class="mention hashtag" rel="tag">#<span>newsletter</span></a> about <a href="https://mastodon.social/tags/fullstack" class="mention hashtag" rel="tag">#<span>fullstack</span></a> <a href="https://mastodon.social/tags/web" class="mention hashtag" rel="tag">#<span>web</span></a> <a href="https://mastodon.social/tags/development" class="mention hashtag" rel="tag">#<span>development</span></a> — Manually curated by andreaman87 &amp; loige.co</p>',
      url: 'https://mastodon.social/@fstackbulletin',
      avatar: 'https://files.mastodon.social/accounts/avatars/110/612/338/021/214/317/original/72888a67caa2555a.jpg',
      avatar_static: 'https://files.mastodon.social/accounts/avatars/110/612/338/021/214/317/original/72888a67caa2555a.jpg',
      header: 'https://mastodon.social/headers/original/missing.png',
      header_static: 'https://mastodon.social/headers/original/missing.png',
      followers_count: 1,
      following_count: 1,
      statuses_count: 7,
      last_status_at: '2023-06-26',
      noindex: false,
      emojis: [],
      roles: [],
      fields: [
        {
          name: 'Website',
          value: '<a href="https://fullstackbulletin.com" target="_blank" rel="nofollow noopener noreferrer me" translate="no"><span class="invisible">https://</span><span class="">fullstackbulletin.com</span><span class="invisible"></span></a>',
          verified_at: null
        }
      ]
    },
    in_reply_to_id: null,
    in_reply_to_account_id: null,
    reblog: null,
    content: '<p>Stylistic QR Code with stable diffusion (full tutorial 🤯)</p><p><a href="https://antfu.me/posts/ai-qrcode" target="_blank" rel="nofollow noopener noreferrer" translate="no"><span class="invisible">https://</span><span class="">antfu.me/posts/ai-qrcode</span><span class="invisible"></span></a></p>',
    plain_content: null,
    created_at: '2023-06-26T21:45:13.592Z',
    emojis: [],
    replies_count: 0,
    reblogs_count: 0,
    favourites_count: 0,
    reblogged: false,
    favourited: false,
    muted: false,
    sensitive: false,
    spoiler_text: '',
    visibility: 'public',
    media_attachments: [],
    mentions: [],
    tags: [],
    card: {
      url: 'https://antfu.me/posts/ai-qrcode',
      title: 'Stylistic QR Code with Stable Diffusion',
      description: '',
      language: 'en',
      type: 'link',
      author_name: '',
      author_url: '',
      provider_name: '',
      provider_url: '',
      html: '',
      width: 1320,
      height: 693,
      image: 'https://files.mastodon.social/cache/preview_cards/images/065/351/843/original/c670f1144c9041fb.png',
      embed_url: '',
      blurhash: 'U34xlDxu4nIUD%WB%Mt700M{?bxu_3xu9FM{'
    },
    poll: null,
    application: {
      name: 'Web',
      website: null
    },
    language: 'en',
    pinned: false,
    emoji_reactions: [],
    bookmarked: false,
    quote: false
  },
  {
    id: '110612701810379372',
    uri: 'https://mastodon.social/users/fstackbulletin/statuses/110612701810379372',
    url: 'https://mastodon.social/@fstackbulletin/110612701810379372',
    account: {
      id: '110612338021214317',
      username: 'fstackbulletin',
      acct: 'fstackbulletin',
      display_name: 'FullStack Bulletin',
      locked: false,
      bot: false,
      discoverable: true,
      group: false,
      created_at: '2023-06-26T00:00:00.000Z',
      note: '<p>The (self-proclaimed) most awesome weekly <a href="https://mastodon.social/tags/newsletter" class="mention hashtag" rel="tag">#<span>newsletter</span></a> about <a href="https://mastodon.social/tags/fullstack" class="mention hashtag" rel="tag">#<span>fullstack</span></a> <a href="https://mastodon.social/tags/web" class="mention hashtag" rel="tag">#<span>web</span></a> <a href="https://mastodon.social/tags/development" class="mention hashtag" rel="tag">#<span>development</span></a> — Manually curated by andreaman87 &amp; loige.co</p>',
      url: 'https://mastodon.social/@fstackbulletin',
      avatar: 'https://files.mastodon.social/accounts/avatars/110/612/338/021/214/317/original/72888a67caa2555a.jpg',
      avatar_static: 'https://files.mastodon.social/accounts/avatars/110/612/338/021/214/317/original/72888a67caa2555a.jpg',
      header: 'https://mastodon.social/headers/original/missing.png',
      header_static: 'https://mastodon.social/headers/original/missing.png',
      followers_count: 1,
      following_count: 1,
      statuses_count: 7,
      last_status_at: '2023-06-26',
      noindex: false,
      emojis: [],
      roles: [],
      fields: [
        {
          name: 'Website',
          value: '<a href="https://fullstackbulletin.com" target="_blank" rel="nofollow noopener noreferrer me" translate="no"><span class="invisible">https://</span><span class="">fullstackbulletin.com</span><span class="invisible"></span></a>',
          verified_at: null
        }
      ]
    },
    in_reply_to_id: null,
    in_reply_to_account_id: null,
    reblog: null,
    content: '<p>Cyclic Dependency Space Toggles</p><p><a href="https://kizu.dev/cyclic-toggles/" target="_blank" rel="nofollow noopener noreferrer" translate="no"><span class="invisible">https://</span><span class="">kizu.dev/cyclic-toggles/</span><span class="invisible"></span></a></p>',
    plain_content: null,
    created_at: '2023-06-26T21:44:44.559Z',
    emojis: [],
    replies_count: 0,
    reblogs_count: 0,
    favourites_count: 0,
    reblogged: false,
    favourited: false,
    muted: false,
    sensitive: false,
    spoiler_text: '',
    visibility: 'public',
    media_attachments: [],
    mentions: [],
    tags: [],
    card: {
      url: 'https://kizu.dev/cyclic-toggles/',
      title: 'Cyclic Dependency Space Toggles',
      description: 'Over the past few years, I wanted to be able to select a value from a list in CSS by toggling a single custom property. We have the “space toggle” for booleans, and hopefully, one day, we’ll get style queries, but what about today? In this article, I present you with the technique I recently discovered.',
      language: 'en',
      type: 'link',
      author_name: '',
      author_url: '',
      provider_name: '',
      provider_url: '',
      html: '',
      width: 0,
      height: 0,
      image: null,
      embed_url: '',
      blurhash: null
    },
    poll: null,
    application: {
      name: 'Web',
      website: null
    },
    language: 'en',
    pinned: false,
    emoji_reactions: [],
    bookmarked: false,
    quote: false
  }
]

test('It should extract links from a set of tweets', async () => {
  const links = extractLinks(statuses)
  expect(links).toStrictEqual([
    'https://calibreapp.com/blog/content-delivery-networks-guide',
    'https://cloudfour.com/thinks/animated-gif-alternative/',
    'https://hyperfetch.bettertyped.com/',
    'https://sanity-io.github.io/GROQ/GROQ-1.revision1/',
    'https://antfu.me/posts/ai-qrcode',
    'https://kizu.dev/cyclic-toggles/'
  ])
})
