const titles = [
  'Are you craving for more content? We got you covered! 😋',
  'We have more content for you! 🤤',
  'Thirsty for more content? Go, hydrate! 🥤',
  'Here\'s something else you might like! 🤩',
  'Feeling hungry for more content? 🍔',
  'Would you like more content? 🤔',
  'Of course, there\'s more content! 🤓',
  'Sometimes, more is more! 🤯',
  'If you feel like it, here\'s more content! 🤗',
  'If you are bored, maybe this will help! 👇',
  'Here\'s more knowledge for you! 🤓',
  'There\'s always MOAR:',
  'It\'s not over yet! 💪',
  'Don\'t walk away just yet 🏃‍♂️',
  'Hang on, there\'s more stuff here:',
  'Pal, check this out! 👇',
  'Hey, there\'s more! 👇',
  'Cheer up buddy, the content is not over yet! 🤗',
  'Wanna check something else? 🤔',
  'Sometimes 7 is not enough!',
  'This Monday deserves more content! 🪇',
  'How about some more content? 🤔',
  'Long way to Full stack mastery, but here\'s a start! 🤓',
  'In the words of Marshmello: "Check this, Check this, Check this out"! 🎶',
  'You just don\'t get enough, do you? 🤣',
  'Are you still here? Ok, here\'s more... 🤷‍♂️',
  'You ask, we provide! 🤗',
  'Running wild with more content! 🐎',
  'If we could have a penny for every content we have... 🤑',
  'The curation never ends! 👩‍🏫',
  'Here\'s a little gift for you! 🎁',
  'Yup, more more more content:',
  'Are you thirsty for more content? 🚰',
  'More juicy links! 🍑',
  'More content, more fun! 🤩',
  'Just in case you wanna some more...',
  'The party never ends! 🎉',
  'We\'re not done yet! 🤓',
  'Here are a few more gold nuggets! 💰',
  'The search for knowledge never ends! 🔎',
  'Some more food for thought! 🍔',
  'Give me, give me, give me, give me some MOAR! 🤪',
  'This would be a good time to stop, but we won\'t! 🤓',
  'Some secret links here for you! 🤫',
  'The content your full stack teacher doesn\'t want you to know! 🤭',
  'Some more shenanigans! 🤪',
  'Extra content please! 🙏',
  'Something that didn\'t make it to the top 7 (but good stuff still):',
  'We almost forgot about these ones! 🤭',
  'Leaving these other ones here...',
  'You have to BELIEVE in the power of more content! 🙏',
  'Buddy, what about checking these ones before you go? 🤔',
  'The FullStack love never ends! 💖',
  'OK, fine! You can have more content! 😤',
  'OK, not done yet!'
]

export function generateExtraContentTitle (issueNumber) {
  return titles[issueNumber % titles.length]
}
