[workspace]
resolver = "2"
members = [
  "functions/fetch-book",
  "functions/fetch-issue-number",
  "functions/fetch-quote",
  "functions/fetch-sponsor",
  "functions/create-issue-v2",
  "shared",
]
