version = 0.1
[default.deploy.parameters]
stack_name = "fstack-bulletin-create-issue"
resolve_s3 = true
s3_prefix = "fstack-bulletin-create-issue"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
