AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  fstackbulletin - Generates a draft newsletter for the next week

Parameters:
  CacheDir:
    Type: String
    Description: "Path to the cache directory"
    Default: ".cache"
  MastodonBaseUrl:
    Type: String
    Description: "Mastodon server base URL"
    Default: "https://mastodon.social"
  CloudinaryCloudName:
    Type: String
    Description: "Cloudinary cloud name"
    Default: "loige"
  CloudinaryFolder:
    Type: String
    Description: "Cloudinary folder"
    Default: "fsb"
  S3DataBucketName:
    Type: String
    Description: "S3 bucket name where to store data"
    Default: "fullstackbulletin-data"
  MailchimpListId:
    Type: String
    Description: "Mailchimp list id"
    Default: "55ace33899"
  MailchimpTemplateId:
    Type: String
    Description: "Mailchimp list id"
    Default: "10022744"
  MailchimpFromEmail:
    Type: String
    Description: "Mailchimp from email"
    Default: "newsletter@fullstackbulletin.com"
  MailchimpFromName:
    Type: String
    Description: "Mailchimp from name"
    Default: "Fullstack Bulletin"
  MailchimpReplyToEmail:
    Type: String
    Description: "Mailchimp reply to email"
    Default: "admin@fullstackbulletin.com"
  AirtableSponsorsTableId:
    Type: String
    Description: "The Airtable table id for the sponsors data"
    Default: appvAXmhtkJEt9OUH

Resources:
  CreateIssueStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/create_issue.asl.yaml
      DefinitionSubstitutions:
        FetchIssueNumberFunctionArn: !GetAtt FetchIssueNumberFunction.Arn
        CreateIssueFunctionArn: !GetAtt CreateIssueFunction.Arn
        FetchQuoteFunctionArn: !GetAtt FetchQuoteFunction.Arn
        FetchBookFunctionArn: !GetAtt FetchBookFunction.Arn
        FetchSponsorFunctionArn: !GetAtt FetchSponsorFunction.Arn
        FetchLinksFunctionArn: !GetAtt FetchLinksFunction.Arn
      Events:
        HourlyTradingSchedule:
          Type: Schedule
          Properties:
            Description: Runs every Friday at 5PM UTC
            Enabled: True
            Schedule: "cron(0 17 ? * FRI *)"
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref FetchIssueNumberFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref CreateIssueFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref FetchQuoteFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref FetchBookFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref FetchSponsorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref FetchLinksFunction

  FetchIssueNumberFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: functions/fetch-issue-number/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 15
      Architectures:
        - arm64
      Environment:
        Variables:
          URL: "https://buttondown.com/fullstackbulletin/archive/"

  FetchQuoteFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: functions/fetch-quote/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 15
      Architectures:
        - arm64

  FetchBookFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: functions/fetch-book/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 15
      Architectures:
        - arm64

  FetchSponsorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: functions/fetch-sponsor/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 15
      Architectures:
        - arm64
      Policies:
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName: /FullstackBulletin/prod/*
      Environment:
        Variables:
          AIRTABLE_APIKEY: "{{resolve:ssm:/FullstackBulletin/prod/AirtableApiKey}}"
          AIRTABLE_TABLE_ID: !Ref AirtableSponsorsTableId

  FetchLinksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/fetch-links/
      Handler: handler.fetchLinks
      Runtime: nodejs20.x
      Timeout: 60
      Architectures:
        - x86_64
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3DataBucketName
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName: /FullstackBulletin/prod/*
      Environment:
        Variables:
          CACHE_DIR: !Ref CacheDir
          MASTODON_BASE_URL: !Ref MastodonBaseUrl
          MASTODON_ACCESS_TOKEN: "{{resolve:ssm:/FullstackBulletin/prod/MastodonAccessToken}}"
          FACEBOOK_APP_ID: "{{resolve:ssm:/FullstackBulletin/prod/FacebookAppId}}"
          FACEBOOK_APP_SECRET: "{{resolve:ssm:/FullstackBulletin/prod/FacebookAppSecret}}"
          UNSPLASH_ACCESS_KEY: "{{resolve:ssm:/FullstackBulletin/prod/UnsplashAccessKey}}"
          CLOUDINARY_CLOUD_NAME: !Ref CloudinaryCloudName
          CLOUDINARY_API_KEY: "{{resolve:ssm:/FullstackBulletin/prod/CloudinaryApiKey}}"
          CLOUDINARY_API_SECRET: "{{resolve:ssm:/FullstackBulletin/prod/CloudinaryApiSecret}}"
          CLOUDINARY_FOLDER: !Ref CloudinaryFolder
          S3_DATA_BUCKET_NAME: !Ref S3DataBucketName

  CreateIssueFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: functions/create-issue/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 15
      Architectures:
        - arm64
      Policies:
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName: /FullstackBulletin/prod/*
      Environment:
        Variables:
          BUTTONDOWN_API_KEY: "{{resolve:ssm:/FullstackBulletin/prod/ButtondownApiKey}}"
          DRAFT_SUBSCRIBER_ID: "d7c3b447-f046-4755-a26a-b8b90b73d002"
          DRAFT_RECIPIENT_EMAIL: "lucianomammino+fsb@gmail.com"

Outputs:
  CreateIssueFunctionArn:
    Description: "Create Issue Function ARN"
    Value: !Ref CreateIssueFunction
